// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRUWJcAa3nLZXhpbNrjOkxGrLvTjch7ZA',
    appId: '1:1059790659507:web:e370713d31f5ef2dae75c6',
    messagingSenderId: '1059790659507',
    projectId: 'hansol-tiktok-clone',
    authDomain: 'hansol-tiktok-clone.firebaseapp.com',
    storageBucket: 'hansol-tiktok-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeyrfNPNWzyDVEaeLf4DhE67NvZxnSMA8',
    appId: '1:1059790659507:android:60ed4325161e2987ae75c6',
    messagingSenderId: '1059790659507',
    projectId: 'hansol-tiktok-clone',
    storageBucket: 'hansol-tiktok-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJpXics-nmENCZdUn_vNNf1hHR1pItm0Y',
    appId: '1:1059790659507:ios:6c65e27539bebb05ae75c6',
    messagingSenderId: '1059790659507',
    projectId: 'hansol-tiktok-clone',
    storageBucket: 'hansol-tiktok-clone.appspot.com',
    iosBundleId: 'com.hansol.tiktok',
  );
}
